-- WARNING: This schema is for context only and is not meant to be run.
-- Table order and constraints may not be valid for execution.

CREATE TABLE public.agenda_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid NOT NULL,
  user_id uuid NOT NULL,
  title text NOT NULL,
  category text NOT NULL DEFAULT 'custom'::text,
  date date NOT NULL,
  time text NOT NULL DEFAULT '09:00'::text,
  recurrence text NOT NULL DEFAULT 'none'::text,
  notes text,
  notification_id integer,
  completed boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT agenda_items_pkey PRIMARY KEY (id),
  CONSTRAINT agenda_items_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT agenda_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.departure_reminders (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid NOT NULL,
  user_id uuid NOT NULL,
  remind_at timestamp with time zone NOT NULL,
  message text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  fired_at timestamp with time zone,
  capacitor_id integer,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT departure_reminders_pkey PRIMARY KEY (id),
  CONSTRAINT departure_reminders_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT departure_reminders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.emergency_profiles (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  full_name text NOT NULL DEFAULT ''::text,
  date_of_birth date,
  nationality text,
  primary_language text,
  secondary_language text,
  photo_url text,
  blood_type text,
  allergies text,
  medications text,
  current_treatments text,
  current_conditions text,
  medical_notes text,
  insurance_provider text,
  insurance_policy_number text,
  doctor_name text,
  doctor_phone text,
  emergency_contact_1_name text,
  emergency_contact_1_relation text,
  emergency_contact_1_phone text,
  emergency_contact_2_name text,
  emergency_contact_2_relation text,
  emergency_contact_2_phone text,
  show_blood_type boolean NOT NULL DEFAULT true,
  show_allergies boolean NOT NULL DEFAULT true,
  show_conditions boolean NOT NULL DEFAULT true,
  show_medications boolean NOT NULL DEFAULT true,
  show_contacts boolean NOT NULL DEFAULT true,
  show_insurance boolean NOT NULL DEFAULT false,
  show_notes boolean NOT NULL DEFAULT false,
  public_token text NOT NULL DEFAULT encode(gen_random_bytes(24), 'base64url'::text) UNIQUE,
  qr_enabled boolean NOT NULL DEFAULT false,
  consent_public_display boolean NOT NULL DEFAULT false,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  trip_id uuid,
  CONSTRAINT emergency_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT emergency_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.emergency_qr_access_logs (
  id bigint NOT NULL DEFAULT nextval('emergency_qr_access_logs_id_seq'::regclass),
  emergency_profile_id uuid NOT NULL,
  access_type text NOT NULL DEFAULT 'public_view'::text CHECK (access_type = 'public_view'::text),
  source text,
  client_info text,
  token_fingerprint text NOT NULL,
  accessed_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT emergency_qr_access_logs_pkey PRIMARY KEY (id),
  CONSTRAINT emergency_qr_access_logs_emergency_profile_id_fkey FOREIGN KEY (emergency_profile_id) REFERENCES public.emergency_profiles(id)
);
CREATE TABLE public.flight_watches (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  trip_id uuid,
  flight_number text NOT NULL,
  flight_date date NOT NULL,
  last_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  last_checked_at timestamp with time zone,
  active boolean NOT NULL DEFAULT true,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT flight_watches_pkey PRIMARY KEY (id),
  CONSTRAINT flight_watches_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT flight_watches_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.health_conditions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL UNIQUE,
  is_pregnant boolean DEFAULT false,
  is_diabetic boolean DEFAULT false,
  is_hypertensive boolean DEFAULT false,
  has_asthma boolean DEFAULT false,
  has_severe_allergy boolean DEFAULT false,
  has_reduced_mobility boolean DEFAULT false,
  is_traveling_with_baby boolean DEFAULT false,
  is_traveling_with_elderly boolean DEFAULT false,
  is_traveling_with_pet boolean DEFAULT false,
  allergy_details text,
  other_conditions text,
  dietary_restrictions text,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT health_conditions_pkey PRIMARY KEY (id),
  CONSTRAINT health_conditions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.health_medications (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  trip_id uuid,
  name text NOT NULL,
  dose_amount numeric,
  dose_unit USER-DEFINED DEFAULT 'tableta'::dose_unit,
  frequency_label text NOT NULL DEFAULT 'Cada 8 horas'::text,
  times ARRAY DEFAULT '{}'::text[],
  notes text,
  quantity_total integer,
  is_critical boolean DEFAULT false,
  packed boolean DEFAULT false,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT health_medications_pkey PRIMARY KEY (id),
  CONSTRAINT health_medications_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT health_medications_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.itinerary_events (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid NOT NULL,
  user_id uuid NOT NULL,
  day_index integer NOT NULL DEFAULT 0,
  sort_order integer NOT NULL DEFAULT 0,
  type text NOT NULL DEFAULT 'activity'::text,
  title text NOT NULL,
  description text,
  start_time text,
  end_time text,
  place_id uuid,
  confirmation_code text,
  source text NOT NULL DEFAULT 'manual'::text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT itinerary_events_pkey PRIMARY KEY (id),
  CONSTRAINT itinerary_events_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT itinerary_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT itinerary_events_place_id_fkey FOREIGN KEY (place_id) REFERENCES public.trip_places(id)
);
CREATE TABLE public.luggage_photos (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid NOT NULL,
  traveler_id uuid,
  user_id uuid NOT NULL,
  photo_url text NOT NULL,
  storage_path text NOT NULL,
  luggage_size USER-DEFINED NOT NULL DEFAULT 'medium'::luggage_size,
  phase text NOT NULL DEFAULT 'open'::text,
  ai_suggestion text,
  zones jsonb,
  taken_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT luggage_photos_pkey PRIMARY KEY (id),
  CONSTRAINT luggage_photos_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT luggage_photos_traveler_id_fkey FOREIGN KEY (traveler_id) REFERENCES public.travelers(id),
  CONSTRAINT luggage_photos_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.offline_queue (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  event_type text NOT NULL CHECK (event_type = ANY (ARRAY['sos'::text, 'checkin'::text, 'location_update'::text])),
  payload jsonb NOT NULL,
  queued_at timestamp with time zone NOT NULL DEFAULT now(),
  synced_at timestamp with time zone,
  is_synced boolean NOT NULL DEFAULT false,
  CONSTRAINT offline_queue_pkey PRIMARY KEY (id),
  CONSTRAINT offline_queue_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.packing_evidence (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  item_id uuid NOT NULL,
  traveler_id uuid,
  user_id uuid NOT NULL,
  photo_url text NOT NULL,
  storage_path text NOT NULL,
  taken_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT packing_evidence_pkey PRIMARY KEY (id),
  CONSTRAINT packing_evidence_item_id_fkey FOREIGN KEY (item_id) REFERENCES public.packing_items(id),
  CONSTRAINT packing_evidence_traveler_id_fkey FOREIGN KEY (traveler_id) REFERENCES public.travelers(id),
  CONSTRAINT packing_evidence_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.packing_items (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid NOT NULL,
  traveler_id uuid,
  user_id uuid NOT NULL,
  label_key text NOT NULL,
  label text NOT NULL,
  category text NOT NULL DEFAULT 'general'::text,
  quantity integer NOT NULL DEFAULT 1,
  checked boolean NOT NULL DEFAULT false,
  source text NOT NULL DEFAULT 'generated'::text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT packing_items_pkey PRIMARY KEY (id),
  CONSTRAINT packing_items_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT packing_items_traveler_id_fkey FOREIGN KEY (traveler_id) REFERENCES public.travelers(id),
  CONSTRAINT packing_items_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.packing_scan_detections (
  id bigint NOT NULL DEFAULT nextval('packing_scan_detections_id_seq'::regclass),
  session_id uuid NOT NULL,
  packing_item_id uuid,
  detected_label text NOT NULL,
  normalized_label text,
  confidence numeric,
  match_status text NOT NULL CHECK (match_status = ANY (ARRAY['matched'::text, 'missing'::text, 'duplicate'::text, 'uncertain'::text, 'extra'::text])),
  quantity_detected integer NOT NULL DEFAULT 1,
  source text NOT NULL DEFAULT 'vision'::text,
  bbox jsonb,
  raw_payload jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT packing_scan_detections_pkey PRIMARY KEY (id),
  CONSTRAINT packing_scan_detections_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.packing_scan_sessions(id),
  CONSTRAINT packing_scan_detections_packing_item_id_fkey FOREIGN KEY (packing_item_id) REFERENCES public.packing_items(id)
);
CREATE TABLE public.packing_scan_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  trip_id uuid NOT NULL,
  traveler_id uuid,
  suitcase_profile_id uuid,
  status text NOT NULL DEFAULT 'pending'::text CHECK (status = ANY (ARRAY['pending'::text, 'processing'::text, 'completed'::text, 'failed'::text])),
  confidence_avg numeric,
  completion_pct numeric,
  missing_count integer NOT NULL DEFAULT 0,
  duplicate_count integer NOT NULL DEFAULT 0,
  uncertain_count integer NOT NULL DEFAULT 0,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  completed_at timestamp with time zone,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT packing_scan_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT packing_scan_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT packing_scan_sessions_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT packing_scan_sessions_traveler_id_fkey FOREIGN KEY (traveler_id) REFERENCES public.travelers(id),
  CONSTRAINT packing_scan_sessions_suitcase_profile_id_fkey FOREIGN KEY (suitcase_profile_id) REFERENCES public.suitcase_profiles(id)
);
CREATE TABLE public.payments (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  provider USER-DEFINED NOT NULL,
  provider_payment_id text NOT NULL UNIQUE,
  provider_customer_id text,
  amount numeric NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  status USER-DEFINED NOT NULL DEFAULT 'pending'::payment_status,
  plan_purchased USER-DEFINED NOT NULL DEFAULT 'pro'::subscription_plan,
  plan_duration_days integer NOT NULL DEFAULT 365,
  receipt_url text,
  error_message text,
  metadata jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT payments_pkey PRIMARY KEY (id),
  CONSTRAINT payments_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.places_cache (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  place_id text NOT NULL UNIQUE,
  name text,
  address text,
  lat double precision,
  lng double precision,
  rating numeric,
  user_ratings_total integer,
  types ARRAY,
  photo_reference text,
  summary text,
  raw_json jsonb,
  created_at timestamp with time zone DEFAULT now(),
  updated_at timestamp with time zone DEFAULT now(),
  CONSTRAINT places_cache_pkey PRIMARY KEY (id)
);
CREATE TABLE public.profiles (
  id uuid NOT NULL,
  name text NOT NULL DEFAULT ''::text,
  avatar_url text,
  preferred_lang text NOT NULL DEFAULT 'es'::text,
  plan USER-DEFINED NOT NULL DEFAULT 'free'::subscription_plan,
  plan_expires_at timestamp with time zone,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT profiles_pkey PRIMARY KEY (id),
  CONSTRAINT profiles_id_fkey FOREIGN KEY (id) REFERENCES auth.users(id)
);
CREATE TABLE public.push_tokens (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  token text NOT NULL,
  platform text NOT NULL CHECK (platform = ANY (ARRAY['android'::text, 'ios'::text, 'web'::text])),
  is_active boolean NOT NULL DEFAULT true,
  device_id text,
  last_seen_at timestamp with time zone NOT NULL DEFAULT now(),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT push_tokens_pkey PRIMARY KEY (id),
  CONSTRAINT push_tokens_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id)
);
CREATE TABLE public.safety_checkins (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  session_id uuid NOT NULL,
  lat numeric NOT NULL,
  lon numeric NOT NULL,
  accuracy numeric,
  note text,
  checkin_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT safety_checkins_pkey PRIMARY KEY (id),
  CONSTRAINT safety_checkins_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.safety_sessions(id)
);
CREATE TABLE public.safety_sessions (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  trip_id uuid,
  session_type text NOT NULL DEFAULT 'safe_walk'::text CHECK (session_type = ANY (ARRAY['safe_walk'::text, 'safe_return'::text, 'live_share'::text])),
  status text NOT NULL DEFAULT 'active'::text CHECK (status = ANY (ARRAY['active'::text, 'completed'::text, 'expired'::text, 'sos_triggered'::text])),
  companion_token text NOT NULL UNIQUE,
  companion_name text,
  companion_phone text,
  expected_duration_min integer,
  started_at timestamp with time zone NOT NULL DEFAULT now(),
  expected_end_at timestamp with time zone,
  ended_at timestamp with time zone,
  last_checkin_at timestamp with time zone,
  last_lat numeric,
  last_lon numeric,
  last_accuracy numeric,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT safety_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT safety_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT safety_sessions_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.sos_events (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  trip_id uuid,
  lat double precision,
  lon double precision,
  accuracy_meters double precision,
  event_token text NOT NULL UNIQUE,
  token_expires_at timestamp with time zone NOT NULL,
  status text NOT NULL DEFAULT 'sent'::text CHECK (status = ANY (ARRAY['sent'::text, 'delivered'::text, 'acknowledged'::text, 'resolved'::text, 'expired'::text])),
  message_text text,
  sent_to_name text,
  sent_to_phone text,
  sent_via text,
  acknowledged_at timestamp with time zone,
  resolved_at timestamp with time zone,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT sos_events_pkey PRIMARY KEY (id),
  CONSTRAINT sos_events_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT sos_events_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.split_bill_expenses (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  session_id uuid NOT NULL,
  user_id uuid NOT NULL,
  description text NOT NULL,
  amount numeric NOT NULL,
  paid_by text NOT NULL,
  split_among ARRAY NOT NULL DEFAULT '{}'::text[],
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT split_bill_expenses_pkey PRIMARY KEY (id),
  CONSTRAINT split_bill_expenses_session_id_fkey FOREIGN KEY (session_id) REFERENCES public.split_bill_sessions(id),
  CONSTRAINT split_bill_expenses_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.split_bill_sessions (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid,
  user_id uuid NOT NULL,
  title text NOT NULL,
  currency text NOT NULL DEFAULT 'USD'::text,
  participants jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT split_bill_sessions_pkey PRIMARY KEY (id),
  CONSTRAINT split_bill_sessions_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT split_bill_sessions_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.suitcase_layout_plans (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  trip_id uuid NOT NULL,
  traveler_id uuid,
  suitcase_profile_id uuid NOT NULL,
  strategy_version text NOT NULL DEFAULT 'v1'::text,
  layout jsonb NOT NULL,
  notes text,
  generated_by text NOT NULL DEFAULT 'ai_orchestrator'::text,
  status text NOT NULL DEFAULT 'draft'::text CHECK (status = ANY (ARRAY['draft'::text, 'approved'::text, 'applied'::text])),
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT suitcase_layout_plans_pkey PRIMARY KEY (id),
  CONSTRAINT suitcase_layout_plans_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT suitcase_layout_plans_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT suitcase_layout_plans_traveler_id_fkey FOREIGN KEY (traveler_id) REFERENCES public.travelers(id),
  CONSTRAINT suitcase_layout_plans_suitcase_profile_id_fkey FOREIGN KEY (suitcase_profile_id) REFERENCES public.suitcase_profiles(id)
);
CREATE TABLE public.suitcase_profiles (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  trip_id uuid NOT NULL,
  traveler_id uuid,
  name text NOT NULL DEFAULT 'Maleta principal'::text,
  luggage_type text NOT NULL DEFAULT 'checked'::text CHECK (luggage_type = ANY (ARRAY['carry_on'::text, 'checked'::text, 'backpack'::text, 'auto_trunk'::text, 'other'::text])),
  height_cm numeric,
  width_cm numeric,
  depth_cm numeric,
  weight_limit_kg numeric,
  compartments integer NOT NULL DEFAULT 1,
  constraints jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT suitcase_profiles_pkey PRIMARY KEY (id),
  CONSTRAINT suitcase_profiles_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id),
  CONSTRAINT suitcase_profiles_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT suitcase_profiles_traveler_id_fkey FOREIGN KEY (traveler_id) REFERENCES public.travelers(id)
);
CREATE TABLE public.travelers (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  role USER-DEFINED NOT NULL DEFAULT 'adult'::traveler_role,
  age integer,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT travelers_pkey PRIMARY KEY (id),
  CONSTRAINT travelers_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT travelers_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.trip_activities (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid NOT NULL,
  user_id uuid NOT NULL,
  activity_key text NOT NULL,
  name text NOT NULL,
  category text NOT NULL DEFAULT 'leisure'::text,
  estimated_cost numeric,
  currency text NOT NULL DEFAULT 'USD'::text,
  duration_hours numeric,
  tip text,
  booking_url text,
  booking_required boolean NOT NULL DEFAULT false,
  booked boolean NOT NULL DEFAULT false,
  booked_at timestamp with time zone,
  notes text,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_activities_pkey PRIMARY KEY (id),
  CONSTRAINT trip_activities_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT trip_activities_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.trip_budget (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  trip_id uuid NOT NULL,
  category text NOT NULL CHECK (category = ANY (ARRAY['transport'::text, 'accommodation'::text, 'food'::text, 'activities'::text, 'shopping'::text, 'health'::text, 'emergency'::text, 'other'::text])),
  planned_amount numeric NOT NULL DEFAULT 0,
  currency_code text NOT NULL DEFAULT 'USD'::text,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_budget_pkey PRIMARY KEY (id),
  CONSTRAINT trip_budget_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT trip_budget_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.trip_expenses (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  trip_id uuid NOT NULL,
  category text NOT NULL DEFAULT 'other'::text CHECK (category = ANY (ARRAY['transport'::text, 'accommodation'::text, 'food'::text, 'activities'::text, 'shopping'::text, 'health'::text, 'emergency'::text, 'other'::text])),
  amount numeric NOT NULL,
  currency_code text NOT NULL DEFAULT 'USD'::text,
  amount_local numeric,
  exchange_rate numeric,
  description text,
  paid_by text,
  split_session_id uuid,
  expense_date date NOT NULL DEFAULT CURRENT_DATE,
  receipt_url text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_expenses_pkey PRIMARY KEY (id),
  CONSTRAINT trip_expenses_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT trip_expenses_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT trip_expenses_split_session_id_fkey FOREIGN KEY (split_session_id) REFERENCES public.split_bill_sessions(id)
);
CREATE TABLE public.trip_journal_entries (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  user_id uuid NOT NULL,
  trip_id uuid,
  title text,
  body text NOT NULL,
  mood USER-DEFINED,
  tags ARRAY DEFAULT '{}'::text[],
  lat double precision,
  lon double precision,
  place_name text,
  photo_paths ARRAY DEFAULT '{}'::text[],
  entry_date date NOT NULL DEFAULT CURRENT_DATE,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_journal_entries_pkey PRIMARY KEY (id),
  CONSTRAINT trip_journal_entries_user_id_fkey FOREIGN KEY (user_id) REFERENCES auth.users(id),
  CONSTRAINT trip_journal_entries_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id)
);
CREATE TABLE public.trip_places (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid NOT NULL,
  user_id uuid NOT NULL,
  name text NOT NULL,
  address text,
  lat double precision NOT NULL,
  lon double precision NOT NULL,
  category text NOT NULL DEFAULT 'other'::text,
  status text NOT NULL DEFAULT 'want_to_go'::text,
  google_place_id text,
  photo_url text,
  assigned_day_index integer,
  notes text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_places_pkey PRIMARY KEY (id),
  CONSTRAINT trip_places_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT trip_places_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.trip_recommendations (
  id uuid NOT NULL DEFAULT gen_random_uuid(),
  trip_id uuid NOT NULL,
  place_id text NOT NULL,
  category text,
  relevance_score numeric,
  distance_meters integer,
  summary text,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  user_id uuid,
  price_level integer,
  raw_json jsonb,
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  CONSTRAINT trip_recommendations_pkey PRIMARY KEY (id),
  CONSTRAINT fk_trip FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT trip_recommendations_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT trip_recommendations_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.trips (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  user_id uuid NOT NULL,
  title text NOT NULL,
  destination text NOT NULL,
  country_code text,
  lat double precision,
  lon double precision,
  start_date date,
  end_date date,
  duration_days integer NOT NULL DEFAULT 1,
  travel_type USER-DEFINED NOT NULL,
  climate USER-DEFINED NOT NULL DEFAULT 'mild'::climate_type,
  traveler_group USER-DEFINED NOT NULL DEFAULT 'solo'::traveler_group,
  activities ARRAY NOT NULL DEFAULT '{}'::text[],
  laundry_mode USER-DEFINED NOT NULL DEFAULT 'none'::laundry_mode,
  packing_style USER-DEFINED NOT NULL DEFAULT 'normal'::packing_style,
  has_laptop boolean NOT NULL DEFAULT false,
  travel_light boolean NOT NULL DEFAULT false,
  trip_status USER-DEFINED NOT NULL DEFAULT 'planning'::trip_status,
  transport_type USER-DEFINED,
  origin_city text,
  origin_lat double precision,
  origin_lon double precision,
  flight_number text,
  airline text,
  airport_code text,
  flight_departure_time text,
  bus_terminal text,
  train_station text,
  cruise_port text,
  currency_code text,
  language_code text,
  number_of_adults integer NOT NULL DEFAULT 1,
  number_of_kids integer NOT NULL DEFAULT 0,
  number_of_babies integer NOT NULL DEFAULT 0,
  weather_forecast jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  risk_level text,
  risk_summary jsonb,
  risk_updated_at timestamp with time zone,
  share_token text UNIQUE,
  share_enabled boolean NOT NULL DEFAULT false,
  share_updated_at timestamp with time zone,
  CONSTRAINT trips_pkey PRIMARY KEY (id),
  CONSTRAINT trips_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);
CREATE TABLE public.wallet_docs (
  id uuid NOT NULL DEFAULT uuid_generate_v4(),
  trip_id uuid NOT NULL,
  user_id uuid NOT NULL,
  doc_type text NOT NULL DEFAULT 'document'::text,
  file_name text,
  mime_type text,
  storage_path text NOT NULL,
  public_url text,
  parsed_data jsonb,
  created_at timestamp with time zone NOT NULL DEFAULT now(),
  updated_at timestamp with time zone NOT NULL DEFAULT now(),
  expiration_date date,
  ocr_name text,
  ocr_doc_number text,
  is_reported_lost boolean NOT NULL DEFAULT false,
  lost_reported_at timestamp with time zone,
  CONSTRAINT wallet_docs_pkey PRIMARY KEY (id),
  CONSTRAINT wallet_docs_trip_id_fkey FOREIGN KEY (trip_id) REFERENCES public.trips(id),
  CONSTRAINT wallet_docs_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id)
);